import { SitePageShell } from "@/components/layout/SitePageShell";

const events = [
  ["class","Weekly session","社課","09.18 THU","#05 Scraping MOPS with Python: from crawler to a usable table","社課 #05｜用 Python 抓公開資訊觀測站：從爬蟲到能用的資料表","Bring a laptop. You leave with a working script and a cleaned dataset of TWSE filings.","自備筆電。結束時帶走一支能跑的腳本，和一份整理好的上市櫃申報資料。","19:00–21:00 · Commerce 260301","19:00–21:00 · 商學院 260301","Open","開放報名","tag tag--ok"],
  ["workshop","Workshop","工作坊","09.27 SAT","Credit risk in practice: from LendingClub data to an explainable scorecard","信用風險模型實作：從 LendingClub 資料到一張說得清楚的評分卡","Half a day, teams of three. A risk manager from a mid-size bank reviews every scorecard at the end.","半天，三人一組。結束前由中型銀行的風控主管逐組檢視每張評分卡。","13:30–17:30 · Commerce 261101","13:30–17:30 · 商學院 261101","8 seats left","剩 8 位","tag tag--warn"],
  ["reading","Reading group","讀書會","10.02 THU","“The Pay Off” ch. 1–3: the invisible rails behind every payment","《The Pay Off》第 1–3 章：每一筆支付背後那條看不見的軌道","Read first, argue second. Online, 90 minutes, one person leads each chapter.","先讀再吵。線上進行，90 分鐘，每章由一個人帶讀。","20:00–21:30 · Online","20:00–21:30 · 線上","Open","開放報名","tag tag--ok"],
  ["class","Weekly session","社課","10.09 THU","#06 Reading a financial statement like a credit analyst, not a student","社課 #06｜用信用分析師的方式讀財報，而不是學生的方式","We take one real filing apart together and find the three lines that actually change the decision.","一起拆一份真的財報，找出真正會改變判斷的那三行。","19:00–21:00 · Commerce 260301","19:00–21:00 · 商學院 260301","Open","開放報名","tag tag--ok"],
  ["workshop","Workshop","工作坊","10.25 SAT","Building a LINE bot that answers questions about your own documents","做一個能回答自家文件問題的 LINE Bot","No prior backend experience needed. By 5pm your bot answers questions about a PDF you brought.","不需要後端經驗。五點前，你的 bot 會回答你自己帶來的 PDF 的問題。","13:00–17:00 · Commerce 261101","13:00–17:00 · 商學院 261101","Opens 10.10","10.10 開放","tag"],
  ["reading","Reading group","讀書會","10.30 THU","Berg et al. (2020): does your phone really predict default?","Berg et al. (2020)：你的手機真的能預測違約嗎？","One paper, one hour of attacking its identification strategy. Come having actually read it.","一篇論文，一小時攻擊它的識別策略。請真的讀完再來。","20:00–21:30 · Online","20:00–21:30 · 線上","Opens 10.16","10.16 開放","tag"],
  ["annual","Annual conference","年會","12.13 SAT","FTL Annual 2026 — every project, defended in public","FTL 年會 2026｜所有專案，公開答辯","Every team presents to mentors, alumni and anyone who shows up. Questions are not softened. Open to the public.","每組向業師、校友與任何到場的人簡報。提問不會放水。對外開放。","09:30–17:00 · Commerce Intl. Conference Hall","09:30–17:00 · 商學院國際會議廳","Opens 11.01","11.01 開放","tag"],
  ["class","Weekly session","社課","11.06 THU","#07 Backtesting: five ways to accidentally lie to yourself","社課 #07｜回測：五種不小心騙自己的方法","We take a strategy with a beautiful equity curve and break it, one bias at a time.","拿一個曲線很漂亮的策略，一次加一種偏誤，把它拆掉。","19:00–21:00 · Commerce 260301","19:00–21:00 · 商學院 260301","Opens 10.23","10.23 開放","tag"],
] as const;

export function EventsPage() {
  return <SitePageShell><main id="main" className="page">
    <section className="pagehead"><div className="wrap reveal"><span className="eyebrow" data-en="Events">活動</span><h1 className="h1" data-en="Four formats, one rule: you leave with something you didn’t have">四種形式，一條規則：離開時要帶走你原本沒有的東西</h1><p className="lead" data-en="Weekly sessions build skills, workshops build artefacts, reading groups build arguments, and the annual conference puts all of it in front of people who will judge it.">社課練技能、工作坊產出東西、讀書會練吵架、年會把這些放到會評斷它們的人面前。</p></div></section>
    <section className="section--tight section"><div className="wrap">
      <div className="filters reveal" data-filter-group="" data-filter-target="#event-list" data-filter-empty="#event-empty" role="group" aria-label="活動類型篩選">
        {[['all','All','全部'],['class','Weekly sessions','社課'],['workshop','Workshops','工作坊'],['reading','Reading groups','讀書會'],['annual','Annual conference','年會']].map(([cat,en,zh],i)=><button className="filter" type="button" data-filter={cat} aria-pressed={i===0} data-en={en} key={cat}>{zh}</button>)}
      </div>
      <div className="grid grid-3" id="event-list" data-stagger="">{events.map(([cat,tagEn,tagZh,date,titleEn,titleZh,bodyEn,bodyZh,timeEn,timeZh,stateEn,stateZh,stateClass])=><a className="card reveal" href="#" data-cat={cat} key={date}><div className="card__top"><span className={cat==='workshop'||cat==='annual'?'tag tag--cyan':cat==='reading'?'tag tag--ok':'tag'} data-en={tagEn}>{tagZh}</span><span className="card__index num">{date}</span></div><h3 className="h3" data-en={titleEn}>{titleZh}</h3><p className="card__body" data-en={bodyEn}>{bodyZh}</p><div className="card__foot dim" style={{fontSize:'.82rem'}}><span data-en={timeEn}>{timeZh}</span><span className={stateClass} data-en={stateEn}>{stateZh}</span></div></a>)}</div>
      <div className="empty" id="event-empty" data-show="false"><svg className="icon" aria-hidden="true"><use href="#i-calendar" /></svg><p data-en="Nothing scheduled in this format right now. The LINE bot will ping you when there is.">這個類型目前沒有排定的場次。有的時候 LINE Bot 會通知你。</p><a className="btn" href="/contact/" data-en="Add the LINE Bot">加入 LINE Bot</a></div>
    </div></section>
  </main></SitePageShell>;
}
